services:
  - type: web
    name: classroom-management-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:combined_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
